In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from sodapy import Socrata
import os.path

In [34]:
def pull_data():
    
    if os.path.isfile("data/case_data.pkl"):
        results_df = pd.read_pickle("data/case_data.pkl")
    else:
        # API usage: https://dev.socrata.com/foundry/data.cdc.gov/vbim-akqf
        client = Socrata("data.cdc.gov", None)
        results = client.get("vbim-akqf", where="cdc_case_earliest_dt > '2021-07-01T00:00:00.000'", limit=10000000)
        results_df = pd.DataFrame.from_records(results)

        # save a copy
        results_df.to_pickle("data/case_data.pkl")
        
    return results_df

In [38]:
results_df = pull_data()

In [39]:
results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 349275 entries, 0 to 349274
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   cdc_case_earliest_dt     349275 non-null  object
 1   cdc_report_dt            317069 non-null  object
 2   current_status           349275 non-null  object
 3   sex                      349275 non-null  object
 4   age_group                349275 non-null  object
 5   race_ethnicity_combined  349275 non-null  object
 6   hosp_yn                  349275 non-null  object
 7   icu_yn                   349275 non-null  object
 8   death_yn                 349275 non-null  object
 9   medcond_yn               349275 non-null  object
 10  pos_spec_dt              85112 non-null   object
 11  onset_dt                 177550 non-null  object
dtypes: object(12)
memory usage: 32.0+ MB

In [40]:
results_df.head()

,cdc_case_earliest_dt,cdc_report_dt,current_status,sex,age_group,race_ethnicity_combined,hosp_yn,icu_yn,death_yn,medcond_yn,pos_spec_dt,onset_dt
0,2021-07-02T00:00:00.000,2021-07-02T00:00:00.000,Probable Case,Male,10 - 19 Years,"Black, Non-Hispanic",Missing,Missing,No,Missing,NaN,NaN
1,2021-07-02T00:00:00.000,2021-07-07T00:00:00.000,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",Missing,Missing,Missing,Yes,2021-07-02T00:00:00.000,NaN
2,2021-07-02T00:00:00.000,2021-07-13T00:00:00.000,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,Missing,No,Missing,NaN,2021-07-02T00:00:00.000
3,2021-07-02T00:00:00.000,NaN,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",Missing,Missing,No,Missing,NaN,NaN
4,2021-07-02T00:00:00.000,2021-07-08T00:00:00.000,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,Missing,No,Missing,NaN,2021-07-02T00:00:00.000